services:
  - type: web
    name: gestionetudiant
    env: docker
    plan: free
    branch: principal
    repo: https://github.com/Nife29/gestionetudiant
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: |
      php artisan config:cache &&
      php artisan route:cache &&
      php artisan view:cache &&
      php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://gestionetudiant-6oaa.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d4e7htrgk3sc73bi9iv0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: gestion_etudiants
      - key: DB_USERNAME
        value: gestion_etudiants_8ct0_user
      - key: DB_PASSWORD
        value: wNGIDVWYLcdpvvns77I5m1yElZGGIuJz